spring:
  application:
    name: xp-news-backend

  profiles:
    active: test

  jpa:
    open-in-view: false

cors:
  origin-patterns: "http://127.0.0.1:5500,http://localhost:8080,http://localhost:63342"
